### ISSUE TITLE
Travis-ci builds do not run

### ISSUE THREAD

**Issue by mpeterv** [RobotGame/rgkit#13]
https://travis-ci.org/RobotGame/rgkit - first and last build was 3 months ago, and there were no builds for recent pull requests.

**Comment by mueslo** [comment]
Yeah, I noticed the same thing yesterday. Not sure why it isn't running (where are the logs?) or where to change it. Maybe it's something only @WhiteHalmos can do?

**Comment by WhiteHalmos** [comment]
Looking into this.

**Comment by WhiteHalmos** [comment]
Seems to be running for now... will reopen if otherwise.
