### ISSUE TITLE
Extract rgkit system dependencies

### ISSUE THREAD

**Issue by WhiteHalmos** [RobotGame/rgkit#20]
Remove imports of modules like sys and os in rgkit.

See https://github.com/RobotGame/rgsandbox/blob/master/rungame.py#L238.

**Comment by mueslo** [comment]
Why? All a bot needs access to is rgkit.settings and rgkit.rg, right?

**Comment by WhiteHalmos** [comment]
True.

**Comment by WhiteHalmos** [comment]
No longer necessary.
