### ISSUE TITLE
filter_out should be a set?

### ISSUE THREAD

**Issue by fraho** [RobotGame/rgkit#31]
Hi,

The doc on the website shows an example of filter_out as a tuple:
https://robotgame.net/rgdocs
```rg.locs_around(self.location, filter_out=('invalid', 'obstacle'))```

But reading at the rg.py code, it needs to be a set. If you pass a tuple, it won't fail and it'll silently return all the locations (i.e. no filtering out at all). Can the doc be updated?

Thanks

**Comment by WhiteHalmos** [comment]
Huh... good catch.

I think it should work both with a set and a tuple, i.e. convert it to a set in locs_around.

**Comment by WhiteHalmos** [comment]
Oh... doesn't it already do that? https://github.com/RobotGame/rgkit/blob/master/rgkit/rg.py#L51

**Comment by fraho** [comment]
Indeed. Don't know how I got it wrong in the first place. Would have been surprising that no one caught that one before! Thanks vm Peter.

**Comment by WhiteHalmos** [comment]
np! Glad to help. :)
