### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mueslo** [RobotGame/rgkit#9]

**Comment by mpeterv** [comment]
What exactly is not working right now with python 3?

**Comment by mpeterv** [comment]
Working on this on [python3](https://github.com/RobotGame/rgkit/tree/python3) branch.

**Comment by mpeterv** [comment]
Should be fixed in #14, though I think the issue should only closed once we get python 3 testing working on travis-ci.

**Comment by WhiteHalmos** [comment]
Working now and travis-ci tests python 3.4. Good job @mpeterv!
